# deployment.yaml

# minikube start
# kubectl create namespace truck-company
# minikube docker-env | Invoke-Expression
# docker build -t truck-company-service:1.0.0 .
# minikube docker-env --unset | Invoke-Expression
apiVersion: apps/v1
kind: Deployment
metadata:
  name: truck-company-app
  namespace: truck-company
spec:
  replicas: 2
  selector:
    matchLabels:
      app: truck-company
  template:
    metadata:
      labels:
        app: truck-company
    spec:
      containers:
        - name: truck-company-app
          image: truck-company-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
            - name: MYSQL_DATABASE
              value: "truckcompany"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "12345"
---
apiVersion: v1
kind: Service
metadata:
  name: truck-company-service
  namespace: truck-company
spec:
  selector:
    app: truck-company
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: truck-company-mariadb
  namespace: truck-company
spec:
  serviceName: "truck-company-mariadb"
  replicas: 1
  selector:
    matchLabels:
      app: truck-company
  template:
    metadata:
      labels:
        app: truck-company
    spec:
      containers:
        - name: truck-company-mariadb
          image: mariadb:10.11.3
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
            - name: MYSQL_DATABASE
              value: "truckcompany"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "12345"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: truck-company-mariadb
  namespace: truck-company
spec:
  selector:
    app: truck-company
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: truck-company-redis
  namespace: truck-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truck-company
  template:
    metadata:
      labels:
        app: truck-company
    spec:
      containers:
        - name: truck-company-redis
          image: redis:7.2.3
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: truck-company-redis
  namespace: truck-company
spec:
  selector:
    app: truck-company
  ports:
    - protocol: TCP
      port: 6379
