http:
  host: "0.0.0.0"
xpack:
  monitoring:
    enabled: true
    elasticsearch:
      username: 'admin'
      password: 'adminadmin'
      hosts: ["http://elasticsearch:9200"]
      ssl:
        verification_mode: none